### ISSUE TITLE
integrate zrobot in rack/webserver of digital me

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/digital_me#12]
- fork repo to new account
- get templates of zero-robot
- see how to load all or subsection of the robot templates
- create gedis example where we work with the services of zrobot directly without rest

**Comment by zaibon** [comment]
```python
rack = j.servers.gworld.server_rack_get()
rack.add('zrobto1', robot)
rack.start()
```
This code already works today. But I have a problem since 0-robot expect python to be monkey patched to properly work. How does gedis support this requirement ?

> create gedis example where we work with the services of zrobot directly without rest

I'll need some more input  about this.

**Comment by andrewayoub** [comment]
b6878f22244d2fd85356b674274c0ac340daf368
