### ISSUE TITLE
useless argument in `server_rack_get`

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/digital_me#20]
I was looking at the prototype of the method `server_rack_get`: 
https://github.com/threefoldtech/digital_me/blob/dd502cf6de2a9e71ba525835b677a7bfd0cb4d18/DigitalMeLib/servers/geventworld/World.py#L20

there are 2 argument while actually only one is enough. `monitor` argument doesn't bring anything, you can just check if `gedis_instance_name` (way too long name too, instance and name are redundant) is None or not, and if it's not None, you enable monitoring

**Comment by andrewayoub** [comment]
fixed as part of refactoring in this commit  b6878f22244d2fd85356b674274c0ac340daf368
