### ISSUE TITLE
move zero-robot portal (js9) into digital me infra

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/digital_me#21]
- we have existing portal which has macro's, ... to visualize zero-robot
- integrate in a new blueprint  (use same flask webserver)
- is optional (when using start.py can be chosen to add to rack or not)
- checkout required git repo's as part of enablement 

## checklist
- [ ] only use toml config file (no more hrd)
- [ ] minimal portal runs again (use the start.sh script & admin user in config file)
- [ ] no longer mogodb, will have to use a digital me client for any model info
- [ ] get zrobot macro's to work
- [ ] authentication uses same user db as digital me

**Comment by despiegk** [comment]
a lot of work has already been done,

new repo:
https://github.com/threefoldtech/jumpscale_portal_classic

get the start.py to work on
https://github.com/threefoldtech/jumpscale_portal_classic/tree/development/apps/portalminimal

right now the portal is blocked somewhere, don't know why

**Comment by despiegk** [comment]
suggest to spend < 1 day on it, 

if things will get too complex then we will have to redo the zero-robot admin portal directly in digital.me

but then we need to make sure we can remake zero-robot admin < 1 week from now

**Comment by rkhamis** [comment]
How are we going to do that? Do we have macro support yet? @despiegk

**Comment by despiegk** [comment]
not doable is too much
