### ISSUE TITLE
j.data.bcdc.zdbclient does not exist

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/digital_me#32]
at various points bcdb.zdbclient is referred to, however it does not exist.  there *is* however something set up called bcdb.zdbclient.  in data/bcdb/BCDB.py, there is no occurrence anywhere of zdbclient being assigned to self, it is always self.dbclient.

**Comment by BolaNasr** [comment]
i think it's not an issue 
```
In [5]:  j.data.bcdb.get?
Signature: j.data.bcdb.get(dbclient, reset=False)
```
because it's take dbclient as a parameter
