### ISSUE TITLE
error in g8storclient

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/digital_me#4]
![image](https://user-images.githubusercontent.com/6021844/43672609-fe218234-97b1-11e8-96c4-7aa04aecce44.png)

**Comment by despiegk** [comment]
was on mac osx, for what do we use this one?

**Comment by maxux** [comment]
This library was used to chunk and compress data. This was never ported and tried on OSX.
This is the library which was modified recently to do blake2, etc.

I'm checking now how fix this problem.
