### ISSUE TITLE
Solve security vulnerability

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/digital_me#42]
![2018-09-24_1824x317_scrot](https://user-images.githubusercontent.com/303164/45939777-5df3d400-bfd5-11e8-9896-42796cd4cf94.png)
![2018-09-24_523x439_scrot](https://user-images.githubusercontent.com/303164/45939781-60562e00-bfd5-11e8-81cb-e3b575006d96.png)

**Comment by rkhamis** [comment]
done
