### ISSUE TITLE
Flist for digital_me

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/digital_me#43]
We need to be able to build farmer DM with 3bot flist to deploy on any container

**Comment by BolaNasr** [comment]
https://hub.grid.tf/tf-autobuilder/threefoldtech-digital_me-autostart-development_simple.flist.md

https://github.com/threefoldtech/digital_me/blob/development_simple/utils/flist.sh
https://github.com/threefoldtech/digital_me/blob/development_simple/utils/startup.toml

**Comment by BolaNasr** [comment]
Steps to verify:
```
In [1]: node = j.clients.zos.get_by_id('ac1f6b272370')   

In [2]: node.containers.create('test','https://hub.grid.tf/tf-autobuilder/threefoldtech-digital_me-aut
   ...: ostart-development_simple.flist',nics=[{'name':'nat0','type':'default'},{'name':
   ...: 'zerotier','type':'zerotier','id':'YOUR_ZT_ID'}])

then 
goto ZT ip of continer  like (10.144.109.136:8000/chat/session/farmer_bot)

**Comment by siddiquagig** [comment]
Verified:
```
In [5]: node = j.clients.zos.get_by_id('ac1f6b272260')

In [5]: node.containers.create('test2','https://hub.grid.tf/tf-autobuilder/threefoldtech-digital_me-autostart-development_simple.flist',nics=[{'name':'nat0','type':'default'},{'name':'zerotier','type':'zerotier','id':'2e1ee8f478'}])

In [6]: cont2= node.containers.get('test2')

In [7]: cont2.mgmt_addr
Out[7]: '10.147.20.165'
```

then opening 10.147.20.165:8000/chat/session/farmer_bot : 
![chatbot](https://user-images.githubusercontent.com/25789724/47433803-30f03800-d7b2-11e8-81c8-df68d2890e8e.jpg)
