### ISSUE TITLE
Segmentation Fault in digital me

### ISSUE THREAD

**Issue by arahmanhamdy** [threefoldtech/digital_me#53]
When we installed digitalme on ubuntu 18.04 zos container, after two days of using 3bot it gave suddenly a segmentation fault. need more investigation to get more info

**Comment by zaibon** [comment]
No logs, Stack trace or anything?

**Comment by arahmanhamdy** [comment]
nothing at all, just segmentation fault

**Comment by zaibon** [comment]
segmentation fault create code dumps information. Next time you see it happening, tries to get as much information about the environment, the process the system. now we're too blind to investigate

**Comment by rkhamis** [comment]
@arahmanhamdy let's deploy a 3bot and watch it for a few days to see if anything will happen.

I'll keep this issue open so we keep monitoring it
