### ISSUE TITLE
Chat bot websocket error

### ISSUE THREAD

**Issue by arahmanhamdy** [threefoldtech/digital_me#54]
Chatbot can't get to the webscoket server if served over https

**Comment by zaibon** [comment]
https://github.com/threefoldtech/digital_me/commit/f5ca8b82d1131d75b15e080a9d6b66e9c38ec39b
is not valid solution for this problem. This patch force the chat bot to be running behind a web proxy that set `X-Forwarded-Proto` header. This is completely wrong. You should never enforce such a hard dependencies on your architecture when writing code. The chat bot need to be able to run anywhere. You don't know where it will be running so you cannot make the assumption that such an header will always be there.

**Comment by ahmadnazih** [comment]
https://github.com/threefoldtech/digital_me/commit/9bc29e8f874e36982a4a00ad7ba9fd3a52f5bf21
@zaibon is it what you mean ?

**Comment by zaibon** [comment]
> 9bc29e8
@zaibon is it what you mean ?

This is already better indeed

**Comment by Pishoy** [comment]
@andrewayoub  when we use a reverse proxy to test https, i can not reach 3bot from reverse proxy as gedis sever is binding to localhost as below 
![1](https://user-images.githubusercontent.com/21987477/47964563-821aea00-e044-11e8-80da-4445794abfaa.jpg)

- DM version 
```

commit 42a0396c08e0034a7557766b3c8c0d28708be496 (HEAD -> development_simple, origin/development_simple)
Author: adelsamar <adels@greenitglobe.com>
Date:   Sun Nov 4 12:16:18 2018 +0200

    Fix paths
```

**Comment by Pishoy** [comment]
also when test https requests i got a looping on request and does not working well with https due to reverse proxy 
need to change ws protocol on request to wss protocol 
![2](https://user-images.githubusercontent.com/21987477/47965130-a7f7bd00-e04b-11e8-8e7a-79e000ba69fb.png)

**Comment by Pishoy** [comment]
verified 
nginx was needing a proper configuration to forward https requests to gedis server as below 
```
        server_name localhost;
        location / {
                proxy_pass http://172.17.0.3:8000;
                proxy_buffering off;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Referer "";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
```
