### ISSUE TITLE
add home page to the 3bot

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/digital_me#55]
currently if we navigate to the `/` of a 3bot we get a 404 not found error. 
We need to have a nice home page that have link to the different part of the 3bot web app

**Comment by siddiquagig** [comment]
When navigating to ```/``` of my 3bot ```http://10.147.17.119:8000/``` , it gives me this page:


![3bot123](https://user-images.githubusercontent.com/25789724/47961552-a8ca2800-e026-11e8-81f4-f3400e809264.JPG)

**Comment by Pishoy** [comment]
confirmed as above and new page as below 
about Digital Me description ,Graphic team are waiting the correct description 
![a](https://user-images.githubusercontent.com/21987477/47984400-2e111380-e0df-11e8-8a72-bd8483c23826.png)


```

**Comment by zaibon** [comment]
Although this robot picture is cute I think we should stay a bit consistent in the image we give to ge 3bot. Can UI team get in touch with @juradoo so they can share and discuss what the 3 bot look like

**Comment by juradoo** [comment]
Hey guys, here is a link to the 3Bot logo and character: https://drive.google.com/open?id=1Rcvdpmv2NQV2NChie34PIxhgvWesHdZZ
I can also have a page background designed that can replace what is currently there.

**Comment by siddiquagig** [comment]
Verified, but the description underneath "Digital Me" is still not in English language.
![newbot](https://user-images.githubusercontent.com/25789724/48061465-7eb86780-e1d8-11e8-9c4e-6db01eec877b.JPG)

**Comment by zaibon** [comment]
> Verified, but the description underneath "Digital Me" is still not in English language.

Indeed please remove the lorem ipsum.
Also the title shoudn't be `DigitalMe`, `DigitalMe` is the name of the technologies/framewrok.
But the public name is 3Bot

**Comment by juradoo** [comment]
Hi @zaibon and team. Who accesses this page and how is it accessed? Working on a design so that it is uniform with 3Bot look/design...just need to know what the functionality (buttons) and info (content/text) on there need to be...can provide the content if you let me know what this is...is it the 3Bot site or wiki or something else? :)

**Comment by juradoo** [comment]
[3BOT - WIKIPAGE SAMPLES - 002.pdf](https://github.com/threefoldtech/digital_me/files/2557160/3BOT.-.WIKIPAGE.SAMPLES.-.002.pdf)

**Comment by siddiquagig** [comment]
Verified
![3bot last](https://user-images.githubusercontent.com/25789724/48309909-8abb7500-e59c-11e8-84e8-cb4db268fca1.JPG)
