### ISSUE TITLE
3bot breadcrumb just keep increasing number forever

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/digital_me#56]
In the 3Bot chat, the number in the breadcrumb just keep increasing every time you do an action.
Once you come back to the home page, the number doesn't return back to 1
![2018-10-31_455x157_scrot](https://user-images.githubusercontent.com/303164/47796315-618d2000-dd24-11e8-98ff-19389510cf1f.png)

**Comment by Pishoy** [comment]
verified
