### ISSUE TITLE
Remove unneeded stuff from 3bot

### ISSUE THREAD

**Issue by arahmanhamdy** [threefoldtech/digital_me#59]
we beed to remove all unneeded stuff (list countries, farmers, etc...)

**Comment by despiegk** [comment]
keep the code though

**Comment by zaibon** [comment]
We just need to remove on development branch, the one dedicated for BD. development_960 can keep everything since we're going to needed later on

**Comment by siddiquagig** [comment]
Unneeded stuff has been removed
![need](https://user-images.githubusercontent.com/25789724/48771769-aa107b80-ecdb-11e8-8d88-e944be36e547.JPG)
