### ISSUE TITLE
3bot needs better error handling

### ISSUE THREAD

**Issue by arahmanhamdy** [threefoldtech/digital_me#61]
we need to figure out a better way for error reporting to the 3bot as it is just keeps loading if any error happened

**Comment by arahmanhamdy** [comment]
21b0c120e2ad7cd882976c8886137079cb95f3a6

**Comment by siddiquagig** [comment]
verified, when entering a wrong jwt while listing domains i get this : 
![error jwt ham](https://user-images.githubusercontent.com/25789724/48066456-1755e400-e1e7-11e8-85af-c68b6e15ca0b.JPG)

**Comment by arahmanhamdy** [comment]
@siddiquagig Why do we still have this issue as open ?

**Comment by siddiquagig** [comment]
#62
