### ISSUE TITLE
DM Flist : gedis server errors can't be handeled with pyredis

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/digital_me#62]
The gedis server needs to use aioredis python library instead of pyredis for error handling, but we can't use aioredis for that. We need to fix the error handling using pyredis

**Comment by zaibon** [comment]
You cannot use aioredis in the 3bot. aioredis is a lib made for asyncio, so it's not compatible with gevent

**Comment by siddiquagig** [comment]
Error handling is fine now and it shows the error:
![correct](https://user-images.githubusercontent.com/25789724/48771448-e2638a00-ecda-11e8-8106-13c701b101ed.JPG)

**Comment by zaibon** [comment]
@siddiquagig reopening this.
From the screen shot I can already 2 problems:
- can't we make the error looks a bit nicer ? Now this looks pretty bland
- The error message is not something you can show to a end user. `code:default:wegateway:list_host` is not understandable by anyone

**Comment by arahmanhamdy** [comment]
The error messages aren't related to the gedis server itself, every chatflow should implement its own messages and exceptions.
