### ISSUE TITLE
our httpclient.ping does not report well on http://radar.threefold.me

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/digital_me#8]
maybe because of redirect?
lets check/fix

**Comment by despiegk** [comment]
also check

https://tokens.threefold.me

**Comment by arahmanhamdy** [comment]
The issue isn't related to the http client, the issue with the site certificate chain 
![image](https://user-images.githubusercontent.com/7352583/43676648-430fb742-97f5-11e8-84e3-b69b5b25638b.png)

**Comment by despiegk** [comment]
can we work around it? ignore the verification failure so we can see if its life?
