### ISSUE TITLE
port threefoldtoken.com website to digital me framework

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/digital_me#9]
keep site in separate git repo

use our checkout trick to get the repo locallaly and then import blueprint from there in gworld ...

**Comment by despiegk** [comment]
is about explaining to ehab & ...
then assign this task to the new owner once they understand what needs to be done

**Comment by arahmanhamdy** [comment]
can't be verified now as digitalme is blocked
https://github.com/threefoldtech/digital_me/issues/31

**Comment by rkhamis** [comment]
This is done now, will put on verification to be reviewed by @despiegk and QA

**Comment by Pishoy** [comment]
@arahmanhamdy , can you write verification steps ?

**Comment by Pishoy** [comment]
verified by installing digitalme using https://github.com/threefoldtech/digital_me/blob/development/install.sh
